create table location (id bigint generated by default as identity (start with 1), lat double, lon double, primary key (id));
    insert into location(id, lat, lon) values (1, 47.497912, 19.04023499999994);
insert into location(id, lat, lon) values (2, 46.6735939, 21.087730899999997);

